# Generated by Django 5.1.3 on 2025-11-16 11:03

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "campus_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campus_code", models.CharField(max_length=20)),
                ("campus_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                (
                    "area_in_acres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_main_campus", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "campuses",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dept_code", models.CharField(max_length=20)),
                ("dept_name", models.CharField(max_length=200)),
                ("hod_name", models.CharField(blank=True, max_length=100, null=True)),
                ("hod_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "floor_numbers",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("timetable_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text=(
                            "Required. 150 characters or fewer. "
                            "Letters, digits and @/./+/-/_ only."
                        ),
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates whether the user can log into this admin site."
                        ),
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin (Platform)"),
                            ("org_admin", "Organization Admin"),
                            ("dean", "Dean"),
                            ("hod", "Head of Department"),
                            ("faculty", "Faculty"),
                            ("student", "Student"),
                            ("staff", "Administrative Staff"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("can_access_multiple_orgs", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(max_length=100)),
                ("batch_code", models.CharField(max_length=20)),
                ("year_of_admission", models.IntegerField()),
                ("current_semester", models.IntegerField()),
                ("section", models.CharField(default="A", max_length=5)),
                ("total_students", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "db_table": "batches",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "faculty_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=30)),
                ("faculty_name", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("assistant_professor", "Assistant Professor"),
                            ("lecturer", "Lecturer"),
                            ("visiting_professor", "Visiting Professor"),
                            ("adjunct_professor", "Adjunct Professor"),
                            ("emeritus_professor", "Emeritus Professor"),
                            ("guest_lecturer", "Guest Lecturer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("specialization", models.CharField(max_length=200)),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("max_teaching_hours_per_week", models.IntegerField(default=18)),
                (
                    "avg_leaves_per_month",
                    models.DecimalField(decimal_places=1, default=1.5, max_digits=3),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_leaving", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_members",
                        to="academics.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "faculty",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("lab", "Lab"),
                            ("tutorial", "Tutorial"),
                            ("practical", "Practical"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                ("is_marked", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.batch",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_sessions",
                        to="academics.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "org_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("org_name", models.CharField(max_length=200)),
                ("short_name", models.CharField(max_length=100)),
                (
                    "institute_type",
                    models.CharField(
                        choices=[
                            ("iit", "Indian Institute of Technology"),
                            ("nit", "National Institute of Technology"),
                            ("iiit", "Indian Institute of Information Technology"),
                            ("central_university", "Central University"),
                            ("state_university", "State University"),
                            ("deemed_university", "Deemed University"),
                            ("private_university", "Private University"),
                            ("autonomous_college", "Autonomous College"),
                            ("affiliated_college", "Affiliated College"),
                            ("polytechnic", "Polytechnic Institute"),
                            ("research_institute", "Research Institute"),
                        ],
                        max_length=30,
                    ),
                ),
                ("established_year", models.IntegerField(blank=True, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial Period"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("subscription_start_date", models.DateField()),
                ("subscription_end_date", models.DateField()),
                ("max_students", models.IntegerField(default=5000)),
                ("max_faculty", models.IntegerField(default=500)),
                (
                    "academic_year_format",
                    models.CharField(default="2024-25", max_length=20),
                ),
                ("current_academic_year", models.CharField(max_length=20)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("primary_color", models.CharField(default="#0066CC", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "indexes": [
                    models.Index(fields=["org_code"], name="org_code_idx"),
                    models.Index(
                        fields=["subscription_status", "is_active"],
                        name="org_status_idx",
                    ),
                    models.Index(fields=["institute_type"], name="org_type_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="faculty",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_members",
                to="academics.organization",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academics.organization",
            ),
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "classroom_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("classroom_code", models.CharField(max_length=20)),
                ("building_name", models.CharField(max_length=100)),
                ("floor_number", models.IntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("lecture_hall", "Lecture Hall"),
                            ("seminar_hall", "Seminar Hall"),
                            ("tutorial_room", "Tutorial Room"),
                            ("laboratory", "Laboratory"),
                            ("auditorium", "Auditorium"),
                            ("smart_classroom", "Smart Classroom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("seating_capacity", models.IntegerField()),
                ("has_projector", models.BooleanField(default=False)),
                ("has_ac", models.BooleanField(default=False)),
                ("has_smart_board", models.BooleanField(default=False)),
                ("has_lab_equipment", models.BooleanField(default=False)),
                ("has_computers", models.BooleanField(default=False)),
                ("computer_count", models.IntegerField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="academics.campus",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classrooms",
                        to="academics.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="academics.organization",
                    ),
                ),
            ],
            options={
                "db_table": "classrooms",
            },
        ),
        migrations.AddField(
            model_name="campus",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="academics.organization",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="academics.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="academics.organization",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "program_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_code", models.CharField(max_length=20)),
                ("program_name", models.CharField(max_length=200)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("ug", "Undergraduate"),
                            ("pg", "Postgraduate"),
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                            ("integrated", "Integrated (UG+PG)"),
                            ("phd", "Doctoral (PhD)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_years", models.DecimalField(decimal_places=1, max_digits=3)),
                ("total_semesters", models.IntegerField()),
                ("total_credits", models.IntegerField()),
                ("allow_multiple_entry_exit", models.BooleanField(default=True)),
                (
                    "exit_certificate_1_year",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "exit_diploma_2_years",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "exit_degree_3_years",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("intake_capacity", models.IntegerField()),
                ("min_eligibility", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academics.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academics.organization",
                    ),
                ),
            ],
            options={
                "db_table": "programs",
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="academics.program",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceThreshold",
            fields=[
                ("threshold_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "minimum_percentage",
                    models.FloatField(
                        default=75.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "warning_percentage",
                    models.FloatField(
                        default=80.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_thresholds",
                        to="academics.department",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_thresholds",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_thresholds",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "school_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_code", models.CharField(max_length=20)),
                ("school_name", models.CharField(max_length=200)),
                ("dean_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dean_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("dean_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("building_names", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="academics.campus",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="academics.organization",
                    ),
                ),
            ],
            options={
                "db_table": "schools",
            },
        ),
        migrations.AddField(
            model_name="program",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="academics.school",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academics.school",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("roll_number", models.CharField(max_length=30)),
                ("student_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("current_semester", models.IntegerField()),
                ("current_year", models.IntegerField()),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("date_of_admission", models.DateField()),
                ("expected_graduation_year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("graduated", "Graduated"),
                            ("dropout", "Dropout"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academics.batch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academics.department",
                    ),
                ),
                (
                    "faculty_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advised_students",
                        to="academics.faculty",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academics.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academics.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("biometric", "Biometric"),
                            ("qr", "QR Code"),
                            ("rfid", "RFID"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("verification_time", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.attendancesession",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance_records",
                        to="academics.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records_new",
                        to="academics.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_code", models.CharField(max_length=20)),
                ("subject_name", models.CharField(max_length=200)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("core", "Core/Mandatory"),
                            ("elective", "Elective"),
                            ("open_elective", "Open Elective"),
                            ("minor", "Minor"),
                            ("audit", "Audit Course"),
                            ("value_added", "Value Added Course"),
                            ("skill_course", "Skill Enhancement Course"),
                            (
                                "ability_enhancement",
                                "Ability Enhancement Compulsory Course (AECC)",
                            ),
                            ("interdisciplinary", "Interdisciplinary"),
                        ],
                        default="core",
                        max_length=30,
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("lecture_hours_per_week", models.IntegerField(default=3)),
                ("tutorial_hours_per_week", models.IntegerField(default=0)),
                ("practical_hours_per_week", models.IntegerField(default=0)),
                (
                    "semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("requires_lab", models.BooleanField(default=False)),
                ("lab_batch_size", models.IntegerField(blank=True, null=True)),
                ("max_students_per_class", models.IntegerField(default=60)),
                ("min_classroom_capacity", models.IntegerField(default=60)),
                ("syllabus_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.organization",
                    ),
                ),
                (
                    "prerequisite_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="prerequisite_for",
                        to="academics.subject",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="StudentElectiveChoice",
            fields=[
                (
                    "choice_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("semester", models.IntegerField()),
                ("choice_priority", models.IntegerField(default=1)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.faculty",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_choices",
                        to="academics.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_choices",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "student_elective_choices",
            },
        ),
        migrations.CreateModel(
            name="FacultySubject",
            fields=[
                (
                    "mapping_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preference_level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Most Preferred, 2=Moderate, 3=Can Teach",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("can_handle_lab", models.BooleanField(default=True)),
                ("years_of_experience_teaching", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_mappings",
                        to="academics.faculty",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_mappings",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_subjects",
            },
        ),
        migrations.CreateModel(
            name="BatchSubjectEnrollment",
            fields=[
                (
                    "enrollment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("enrolled_students", models.IntegerField()),
                ("academic_year", models.CharField(max_length=20)),
                ("semester", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="academics.batch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_enrollments",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "batch_subject_enrollments",
            },
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sessions",
                to="academics.subject",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("semester", "Semester"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField()),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.department",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_reports",
            },
        ),
        migrations.CreateModel(
            name="AttendanceAlert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_attendance", "Low Attendance"),
                            ("pending_marking", "Pending Marking"),
                            ("discrepancy", "Discrepancy"),
                            ("threshold_breach", "Threshold Breach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_alerts",
            },
        ),
        migrations.CreateModel(
            name="SubjectEnrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.IntegerField()),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_subject_enrollments",
                        to="academics.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="academics.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "subject_enrollments",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "timeslot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_name", models.CharField(max_length=50)),
                ("slot_order", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("is_break", models.BooleanField(default=False)),
                ("is_lunch", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to="academics.organization",
                    ),
                ),
            ],
            options={
                "db_table": "timeslots",
                "ordering": ["day_of_week", "slot_order"],
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("academic_year", models.CharField(max_length=20)),
                ("semester", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "generation_job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="academics.generationjob",
                    ),
                ),
            ],
            options={
                "db_table": "timetables",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetablePreferences",
            fields=[
                (
                    "pref_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_classes_per_day", models.IntegerField(default=6)),
                ("max_consecutive_classes", models.IntegerField(default=3)),
                ("min_break_duration_minutes", models.IntegerField(default=15)),
                ("lunch_break_start", models.TimeField()),
                ("lunch_break_end", models.TimeField()),
                ("working_days_per_week", models.IntegerField(default=6)),
                ("class_duration_minutes", models.IntegerField(default=60)),
                ("allow_saturday_classes", models.BooleanField(default=True)),
                ("allow_back_to_back_labs", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_preferences",
                        to="academics.organization",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_preferences",
            },
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.batch",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.classroom",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.faculty",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="academics.timetable",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_slots",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="academics.student",
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="academics.timetableslot",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                ("audit_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("override", "Override"),
                        ],
                        max_length=10,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=10, null=True)),
                ("new_status", models.CharField(max_length=10)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="academics.attendancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_audit_logs",
                "indexes": [
                    models.Index(
                        fields=["record", "changed_at"], name="audit_record_time_idx"
                    ),
                    models.Index(fields=["changed_by"], name="audit_changed_by_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="faculty",
            index=models.Index(
                fields=["organization", "department", "is_available"],
                name="fac_org_dept_avail_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="faculty",
            index=models.Index(fields=["designation"], name="fac_desig_idx"),
        ),
        migrations.AddIndex(
            model_name="faculty",
            index=models.Index(fields=["user"], name="fac_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="faculty",
            unique_together={("organization", "employee_id")},
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["organization", "room_type", "is_available"],
                name="room_org_type_avail_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(fields=["campus"], name="room_campus_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("organization", "classroom_code")},
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(
                fields=["organization", "is_active"], name="campus_org_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campus",
            unique_together={("organization", "campus_code")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "role", "is_active"], name="user_org_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="user_username_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_idx"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["organization", "current_semester", "is_active"],
                name="batch_org_sem_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["program"], name="batch_prog_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={
                ("organization", "program", "year_of_admission", "section")
            },
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["organization", "is_active"], name="school_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["campus"], name="school_campus_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="school",
            unique_together={("organization", "school_code")},
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["organization", "program_type", "is_active"],
                name="prog_org_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["school"], name="prog_school_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["department"], name="prog_dept_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("organization", "program_code")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "is_active"], name="dept_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["school"], name="dept_school_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "school", "dept_code")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["organization", "current_semester", "is_active"],
                name="stu_org_sem_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["batch"], name="stu_batch_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["user"], name="stu_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("organization", "roll_number")},
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "status"], name="record_student_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["session"], name="record_session_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["marked_at"], name="record_marked_at_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["organization", "department", "is_active"],
                name="subj_org_dept_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["program", "semester"], name="subj_prog_sem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["subject_type"], name="subj_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("organization", "subject_code")},
        ),
        migrations.AddIndex(
            model_name="studentelectivechoice",
            index=models.Index(
                fields=["organization", "semester", "is_approved"],
                name="elec_org_sem_appr_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentelectivechoice",
            unique_together={("student", "subject", "semester")},
        ),
        migrations.AddIndex(
            model_name="facultysubject",
            index=models.Index(
                fields=["organization", "subject"], name="facsubj_org_subj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultysubject",
            index=models.Index(
                fields=["faculty", "preference_level"], name="facsubj_fac_pref_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facultysubject",
            unique_together={("faculty", "subject")},
        ),
        migrations.AddIndex(
            model_name="batchsubjectenrollment",
            index=models.Index(
                fields=["organization", "semester"], name="bse_org_sem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchsubjectenrollment",
            index=models.Index(fields=["batch"], name="bse_batch_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="batchsubjectenrollment",
            unique_together={("batch", "subject", "academic_year", "semester")},
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["faculty", "date"], name="session_faculty_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["subject", "date"], name="session_subject_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(fields=["is_marked"], name="session_marked_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["generated_by", "generated_at"], name="report_gen_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(fields=["report_type"], name="report_type_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["student", "is_read"], name="alert_student_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["faculty", "is_read"], name="alert_faculty_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(fields=["created_at"], name="alert_created_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["student", "semester"], name="enroll_student_sem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["subject", "is_active"], name="enroll_subject_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["academic_year", "semester"], name="enroll_year_sem_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together={("student", "subject", "academic_year", "semester")},
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["organization", "day_of_week", "slot_order"],
                name="slot_org_day_order_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("organization", "day_of_week", "start_time")},
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["timetable", "day", "start_time"],
                name="timetable_s_timetab_db7e0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["faculty", "day", "start_time"],
                name="timetable_s_faculty_8ee0a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["classroom", "day", "start_time"],
                name="timetable_s_classro_89dcb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="attendance_student_0943ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["timetable_slot", "date"], name="attendance_timetab_2e03d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "timetable_slot", "date")},
        ),
    ]
