# Generated by Django 5.1.3 on 2025-11-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_generationjob_timetable_generation_job"),
    ]

    operations = [
        # Department model indexes
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_id'], name='dept_id_idx'),
        ),
        
        # Course model indexes
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='course_id_idx'),
        ),
        
        # Faculty model indexes
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['department'], name='faculty_dept_idx'),
        ),
        
        # Student model indexes
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='student_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='student_course_idx'),
        ),
        
        # Batch model indexes
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course'], name='batch_course_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['department'], name='batch_dept_idx'),
        ),
        
        # Subject model indexes
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='subject_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course'], name='subject_course_idx'),
        ),
        
        # Timetable model indexes
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['batch'], name='timetable_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['department'], name='timetable_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['status'], name='timetable_status_idx'),
        ),
        
        # TimetableSlot model indexes
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable'], name='slot_timetable_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['day'], name='slot_day_idx'),
        ),
        
        # GenerationJob model indexes
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status'], name='job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['created_at'], name='job_created_idx'),
        ),
    ]
