# Generated by Django 5.1.3 on 2025-11-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_add_database_indexes"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="batch",
            name="batch_course_idx",
        ),
        migrations.RemoveIndex(
            model_name="batch",
            name="batch_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="dept_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="faculty",
            name="faculty_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="generationjob",
            name="job_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="generationjob",
            name="job_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_course_idx",
        ),
        migrations.RemoveIndex(
            model_name="subject",
            name="subject_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="subject",
            name="subject_course_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetable",
            name="timetable_batch_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetable",
            name="timetable_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetable",
            name="timetable_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableslot",
            name="slot_timetable_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableslot",
            name="slot_day_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("faculty", "Faculty"),
                    ("student", "Student"),
                ],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "department"], name="users_role_dept_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_username_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "role"], name="users_active_role_idx"
            ),
        ),
    ]
