# Generated by Django 5.1.3 on 2025-11-15 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_add_user_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("lab", "Lab"),
                            ("tutorial", "Tutorial"),
                            ("practical", "Practical"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                ("is_marked", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.batch",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_sessions",
                        to="academics.faculty",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("biometric", "Biometric"),
                            ("qr", "QR Code"),
                            ("rfid", "RFID"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("verification_time", models.DateTimeField(blank=True, null=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance_records",
                        to="academics.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records_new",
                        to="academics.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.attendancesession",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
            },
        ),
        migrations.CreateModel(
            name="AttendanceThreshold",
            fields=[
                ("threshold_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "minimum_percentage",
                    models.FloatField(
                        default=75.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "warning_percentage",
                    models.FloatField(
                        default=80.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_thresholds",
                        to="academics.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_thresholds",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_thresholds",
            },
        ),
        migrations.CreateModel(
            name="SubjectEnrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.IntegerField()),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="academics.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="academics.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "subject_enrollments",
            },
        ),
        migrations.CreateModel(
            name="AttendanceAlert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_attendance", "Low Attendance"),
                            ("pending_marking", "Pending Marking"),
                            ("discrepancy", "Discrepancy"),
                            ("threshold_breach", "Threshold Breach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_alerts",
                "indexes": [
                    models.Index(
                        fields=["student", "is_read"], name="alert_student_read_idx"
                    ),
                    models.Index(
                        fields=["faculty", "is_read"], name="alert_faculty_read_idx"
                    ),
                    models.Index(fields=["created_at"], name="alert_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                ("audit_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("override", "Override"),
                        ],
                        max_length=10,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=10, null=True)),
                ("new_status", models.CharField(max_length=10)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="academics.attendancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_audit_logs",
                "indexes": [
                    models.Index(
                        fields=["record", "changed_at"], name="audit_record_time_idx"
                    ),
                    models.Index(fields=["changed_by"], name="audit_changed_by_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("semester", "Semester"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField()),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.department",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_reports",
                "indexes": [
                    models.Index(
                        fields=["generated_by", "generated_at"],
                        name="report_gen_time_idx",
                    ),
                    models.Index(fields=["report_type"], name="report_type_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["faculty", "date"], name="session_faculty_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["subject", "date"], name="session_subject_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(fields=["is_marked"], name="session_marked_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "status"], name="record_student_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["session"], name="record_session_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["marked_at"], name="record_marked_at_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["student", "semester"], name="enroll_student_sem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["subject", "is_active"], name="enroll_subject_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectenrollment",
            index=models.Index(
                fields=["academic_year", "semester"], name="enroll_year_sem_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together={("student", "subject", "academic_year", "semester")},
        ),
    ]
