# Generated by Django 5.1.3 on 2025-11-24 18:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "building_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("building_code", models.CharField(max_length=50)),
                ("building_name", models.CharField(max_length=200)),
                (
                    "building_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "buildings",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=200)),
                (
                    "course_short_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("course_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "course_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("credits", models.IntegerField()),
                ("theory_credits", models.IntegerField(blank=True, null=True)),
                ("practical_credits", models.IntegerField(blank=True, null=True)),
                ("lecture_hours_per_week", models.IntegerField(blank=True, null=True)),
                ("tutorial_hours_per_week", models.IntegerField(blank=True, null=True)),
                (
                    "practical_hours_per_week",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "session_pattern",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "room_type_required",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("min_room_capacity", models.IntegerField(blank=True, null=True)),
                ("room_features_required", models.JSONField(blank=True, null=True)),
                ("corequisite_course_ids", models.JSONField(blank=True, null=True)),
                ("max_enrollment", models.IntegerField(blank=True, null=True)),
                ("min_enrollment", models.IntegerField(blank=True, null=True)),
                (
                    "allow_cross_department_enrollment",
                    models.BooleanField(blank=True, null=True),
                ),
                ("offered_in_odd_semester", models.BooleanField(blank=True, null=True)),
                (
                    "offered_in_even_semester",
                    models.BooleanField(blank=True, null=True),
                ),
                ("offered_in_summer_term", models.BooleanField(blank=True, null=True)),
                ("syllabus_file_url", models.TextField(blank=True, null=True)),
                ("course_objectives", models.TextField(blank=True, null=True)),
                ("course_outcomes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_offered_semester",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_code", models.CharField(max_length=50)),
                ("room_number", models.CharField(max_length=50)),
                ("room_name", models.CharField(blank=True, max_length=200, null=True)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("room_type", models.CharField(max_length=50)),
                ("seating_capacity", models.IntegerField()),
                ("exam_capacity", models.IntegerField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("equipment_description", models.TextField(blank=True, null=True)),
                ("number_of_computers", models.IntegerField(blank=True, null=True)),
                ("specialized_software", models.JSONField(blank=True, null=True)),
                (
                    "is_accessible_for_disabled",
                    models.BooleanField(blank=True, null=True),
                ),
                ("has_lift_access", models.BooleanField(blank=True, null=True)),
                (
                    "allow_cross_department_usage",
                    models.BooleanField(blank=True, null=True),
                ),
                ("priority_department_id", models.UUIDField(blank=True, null=True)),
                ("is_bookable", models.BooleanField(blank=True, null=True)),
                ("maintenance_schedule", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("room_status", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.AlterUniqueTogether(
            name="batchsubjectenrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="batchsubjectenrollment",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="batchsubjectenrollment",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="batchsubjectenrollment",
            name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="campus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="campus",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="campus",
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="department",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="organization",
        ),
        migrations.AlterUniqueTogether(
            name="facultysubject",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="facultysubject",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="facultysubject",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="facultysubject",
            name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="studentelectivechoice",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentelectivechoice",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="studentelectivechoice",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="studentelectivechoice",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentelectivechoice",
            name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subject",
            name="department",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="prerequisite_subjects",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="program",
        ),
        migrations.RemoveField(
            model_name="timetablepreferences",
            name="organization",
        ),
        migrations.RemoveIndex(
            model_name="batch",
            name="batch_org_sem_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="org_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="org_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="school",
            name="school_org_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="school",
            name="school_campus_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="stu_org_sem_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="stu_batch_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="stu_user_idx",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="building_names",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="dean_phone",
            new_name="office_phone",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="date_of_admission",
            new_name="admission_date",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="expected_graduation_year",
            new_name="admission_year",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="phone",
            new_name="emergency_contact_phone",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="student_name",
            new_name="first_name",
        ),
        migrations.RenameIndex(
            model_name="batch",
            new_name="idx_batch_program",
            old_name="batch_prog_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="idx_org_code",
            old_name="org_code_idx",
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="school",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="organization",
            name="academic_year_format",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="current_academic_year",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="established_year",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="institute_type",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="max_faculty",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="max_students",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_end_date",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_start_date",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="subscription_status",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="timetableslot",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_access_multiple_orgs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_ip",
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="organization",
            name="academic_year_start_month",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="faculty_email_domain",
            field=models.CharField(default="faculty.edu", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="nep2020_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CENTRAL_UNIVERSITY", "Central University"),
                    ("STATE_UNIVERSITY", "State University"),
                    ("DEEMED", "Deemed University"),
                    ("PRIVATE", "Private University"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="semester_system",
            field=models.CharField(
                choices=[
                    ("SEMESTER", "Semester"),
                    ("ANNUAL", "Annual"),
                    ("TRIMESTER", "Trimester"),
                ],
                default="SEMESTER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="student_email_domain",
            field=models.CharField(default="student.edu", max_length=100),
        ),
        migrations.AddField(
            model_name="school",
            name="dean_faculty_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="established_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="office_email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="office_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ON_LEAVE", "On Leave"),
                    ("GRADUATED", "Graduated"),
                    ("DROPPED_OUT", "Dropped Out"),
                    ("RUSTICATED", "Rusticated"),
                    ("TRANSFERRED", "Transferred"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="batch_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="current_semester_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="fee_status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partial"),
                    ("WAIVED", "Waived"),
                ],
                default="UNPAID",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_hosteller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="minor_credits_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="minor_dept",
            field=models.ForeignKey(
                blank=True,
                db_column="minor_dept_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minor_students",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pursuing_minor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="room_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="scholarship",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="total_credits_earned",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batch",
            name="current_semester",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="batch",
            name="department",
            field=models.ForeignKey(
                db_column="dept_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="program",
            field=models.ForeignKey(
                blank=True,
                db_column="program_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="total_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department",
            field=models.ForeignKey(
                db_column="dept_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_members",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_members",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schools",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="cgpa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_semester",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_year",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                db_column="dept_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                db_column="program_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                db_column="user_id",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_column="org_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="academics.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("organization", "batch_code")},
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["organization"], name="idx_batch_org"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["department"], name="idx_batch_dept"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["is_active"], name="idx_org_active"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["organization"], name="idx_school_org"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["school_code"], name="idx_school_code"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["organization"], name="idx_student_org"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["department"], name="idx_student_dept"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["program"], name="idx_student_program"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_number"], name="idx_student_enrollment"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["username"], name="idx_student_username"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["email"], name="idx_student_email"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["batch_name"], name="idx_student_batch"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["is_active"], name="idx_student_active"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_year", "current_semester"],
                name="idx_student_year_semester",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="academics.organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                db_column="dept_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="attendancealert",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_alerts",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sessions",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="attendancethreshold",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_thresholds",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="subjectenrollment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="timetableslot",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                db_column="building_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="academics.building",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_column="dept_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="academics.organization",
            ),
        ),
        migrations.AlterField(
            model_name="timetableslot",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.room"
            ),
        ),
        migrations.DeleteModel(
            name="BatchSubjectEnrollment",
        ),
        migrations.DeleteModel(
            name="FacultySubject",
        ),
        migrations.DeleteModel(
            name="StudentElectiveChoice",
        ),
        migrations.DeleteModel(
            name="TimetablePreferences",
        ),
        migrations.RemoveField(
            model_name="school",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="school",
            name="dean_email",
        ),
        migrations.RemoveField(
            model_name="school",
            name="dean_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="faculty_advisor",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["organization"], name="idx_building_org"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["building_code"], name="idx_building_code"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["organization"], name="idx_course_org"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["department"], name="idx_course_dept"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["course_code"], name="idx_course_code"),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["organization"], name="idx_room_org"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["building"], name="idx_room_building"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["room_code"], name="idx_room_code"),
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
    ]
